/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const strictDocScope = process.env.DOCS_STRICT_SCOPE === '1';

const strictSidebar = [
  'cli-examples',
  'github-actions-setup-babysitter',
  'github-actions-setup-claude-code',
  'github-actions-setup-codex',
  'github-actions-setup-gemini-cli',
  {
    type: 'category',
    label: 'Reference',
    items: ['reference/GETTING_STARTED', 'reference/babysitter_cli_surface_spec']
  },
  {
    type: 'category',
    label: 'V6 Roadmap',
    items: ['v6-spec-and-roadmap/README', 'v6-spec-and-roadmap/testing-framework', 'v6-spec-and-roadmap/v6-implementation-roadmap']
  }
];

const curatedSidebar = [
  {
    type: 'category',
    label: 'Start Here',
    collapsible: false,
    items: [
      'user-guide/index',
      'package-and-plugin-map',
      {
        type: 'category',
        label: 'Getting Started',
        items: [
          'user-guide/getting-started/README',
          'user-guide/getting-started/installation',
          'user-guide/getting-started/quickstart',
          'user-guide/getting-started/first-run',
          'user-guide/getting-started/migration',
          'user-guide/getting-started/upgrade-to-v6'
        ]
      },
      {
        type: 'category',
        label: 'Ecosystem & Components',
        items: [
          'user-guide/ecosystem/overview',
          'user-guide/ecosystem/babysitter-sdk',
          'user-guide/ecosystem/adapters',
          'user-guide/ecosystem/atlas',
          'user-guide/ecosystem/genty',
          'user-guide/ecosystem/observer-dashboard',
          'user-guide/ecosystem/kradle',
          'user-guide/ecosystem/kip-sdk'
        ]
      },
      'user-guide/architecture',
      { type: 'autogenerated', dirName: 'user-guide/tutorials' },
      { type: 'autogenerated', dirName: 'user-guide/features' },
      {
        type: 'category',
        label: 'Harnesses',
        items: [
          'user-guide/harnesses/install-matrix',
          'user-guide/harnesses/claude-code',
          'user-guide/harnesses/codex'
        ]
      },
      { type: 'autogenerated', dirName: 'user-guide/reference' }
    ]
  },
  {
    type: 'category',
    label: 'Integrate & Extend',
    items: [
      'assimilation/index',
      { type: 'autogenerated', dirName: 'assimilation/harness' },
      'github-actions-setup-babysitter',
      'github-actions-setup-claude-code',
      'github-actions-setup-codex',
      'github-actions-setup-gemini-cli',
      'plugins',
      { type: 'autogenerated', dirName: 'plugins' },
      'adapters/README',
      { type: 'autogenerated', dirName: 'adapters/tutorials' },
      { type: 'autogenerated', dirName: 'adapters/reference' },
      { type: 'autogenerated', dirName: 'adapters/archive' }
    ]
  },
  {
    type: 'category',
    label: 'Operate & Maintain',
    items: [
      'cli-examples',
      'workspace-validation',
      'release-pipeline',
      { type: 'autogenerated', dirName: 'testing' },
      { type: 'autogenerated', dirName: 'reference' },
      { type: 'autogenerated', dirName: 'agent-reference' }
    ]
  },
  {
    type: 'category',
    label: 'Architecture & Background',
    items: [
      { type: 'autogenerated', dirName: 'v6-spec-and-roadmap' },
      { type: 'autogenerated', dirName: 'articles' }
    ]
  }
];

module.exports = {
  docsSidebar: strictDocScope ? strictSidebar : curatedSidebar
};
