import type { GentyExtension, ExtensionContext } from "@a5c-ai/genty-core/extensions";
import { execSync } from "child_process";
import * as path from "path";

const PLUGIN_ROOT = path.resolve(__dirname, "..");

const COMMANDS = [
  "assimilate",
  "call",
  "cleanup",
  "contrib",
  "doctor",
  "forever",
  "help",
  "observe",
  "plan",
  "plugins",
  "project-install",
  "resume",
  "retrospect",
  "user-install",
  "yolo",
] as const;

function syncSessionEnvironment(): void {
  process.env.GENTY_PLUGIN_ROOT = PLUGIN_ROOT;
}

function sessionStartInput(): Record<string, unknown> {
  syncSessionEnvironment();
  const sessionId = process.env.AGENT_SESSION_ID;
  return {
    event: "session_start",
    cwd: process.cwd(),
    ...(sessionId ? { session_id: sessionId } : {}),
  };
}

/**
 * Run a proxied hook script and return parsed JSON result.
 * Returns empty object on failure (hooks are best-effort).
 */
function runProxiedHook(
  scriptName: string,
  inputData?: Record<string, unknown>
): Record<string, unknown> {
  const scriptPath = path.join(PLUGIN_ROOT, "hooks", scriptName);
  try {
    const result = execSync(`node "${scriptPath}"`, {
      input: inputData ? JSON.stringify(inputData) : undefined,
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30000,
      env: {
        ...process.env,
        GENTY_PLUGIN_ROOT: PLUGIN_ROOT,
      },
    });
    return JSON.parse(result.toString("utf8").trim());
  } catch {
    // Hooks are best-effort -- never break the extension
    return {};
  }
}

const babysitterExtension: GentyExtension = {
  name: "babysitter",
  version: "1.0.0",
  description: "Babysitter orchestration integration for genty",
  permissions: ["commands:register", "events:listen"],

  activate(ctx: ExtensionContext): void {
    // Session start hook
    ctx.onEvent("sessionStart", async () => {
      runProxiedHook("babysitter-proxied-session-start.js", sessionStartInput());
    });

    syncSessionEnvironment();

    // Register /babysit and /babysitter aliases
    ctx.registerCommand("babysit", async (args: string[]) => {
      syncSessionEnvironment();
      ctx.log("info", `Babysitter: forwarding /babysit ${args.join(" ")}`);
    });

    ctx.registerCommand("babysitter", async (args: string[]) => {
      syncSessionEnvironment();
      ctx.log("info", `Babysitter: forwarding /babysitter ${args.join(" ")}`);
    });

    // Register all skill-backed commands
    for (const name of COMMANDS) {
      ctx.registerCommand(name, async (args: string[]) => {
        syncSessionEnvironment();
        ctx.log("info", `Babysitter: forwarding /${name} ${args.join(" ")}`);
      });

      ctx.registerCommand(`babysitter:${name}`, async (args: string[]) => {
        syncSessionEnvironment();
        ctx.log("info", `Babysitter: forwarding /babysitter:${name} ${args.join(" ")}`);
      });
    }

    // Wire orchestration providers from co-located source (generated by extension compiler)
    try {
      const { register } = require('./src/register');
      register();
      ctx.log("info", "Babysitter orchestration providers registered");
    } catch {
      // Provider source not available — orchestration providers not registered
    }

    ctx.log("info", "Babysitter extension activated");
  },
};

export default babysitterExtension;
